from telnetlib import TELNET_PORT

RECEIVER_IP = '192.168.1.24'
RECEIVER_PORT = TELNET_PORT
GUI = True
DEBUG = True

VOL_PRESET_1 = '-30.0dB'
VOL_PRESET_2 = '-24.0dB'
VOL_PRESET_3 = '-18.0dB'

FAV_SRC_1_CODE = 'GAME'
FAV_SRC_1_LABEL = 'Computer HDMI'
FAV_SRC_2_CODE = 'CD'
FAV_SRC_2_LABEL = 'Pro Analog'
FAV_SRC_3_CODE = 'TV'
FAV_SRC_3_LABEL = 'Pro Digital'
